<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\TransaksiDo;
use Illuminate\Http\Request;

class TransaksiDoController extends Controller
{
    public function index(Request $request)
    {
        $perusahaan_id = $request->user()->perusahaan_id;
        
        $query = TransaksiDo::where('perusahaan_id', $perusahaan_id);

        if ($request->has('tanggal')) {
            $query->whereDate('tanggal', $request->tanggal);
        }

        return response()->json(
            $query->with(['supir', 'kendaraan', 'penjual'])->latest()->paginate(20)
        );
    }

    public function show($id, Request $request)
    {
        $perusahaan_id = $request->user()->perusahaan_id;
        
        $transaksi = TransaksiDo::where('perusahaan_id', $perusahaan_id)
            ->with(['supir', 'kendaraan', 'penjual', 'detailTransaksiDo', 'pembayaranHutang'])
            ->findOrFail($id);

        return response()->json($transaksi);
    }

    public function store(Request $request)
    {
        $request->validate([
            'tanggal' => 'required|date',
            'penjual_id' => 'required|exists:penjual,id',
            'supir_id' => 'required|exists:supir,id',
            'no_polisi' => 'nullable|string',
            'tonase' => 'required|numeric',
            'harga_satuan' => 'required|numeric',
            'upah_bongkar' => 'nullable|numeric',
            'biaya_lain' => 'nullable|numeric',
            'keterangan_biaya_lain' => 'nullable|string',
            'cara_bayar' => 'required|in:tunai,transfer,cair di luar,belum dibayar',
        ]);

        $sub_total = $request->tonase * $request->harga_satuan;
        
        $transaksi = TransaksiDo::create([
            'perusahaan_id' => $request->user()->perusahaan_id,
            'nomor' => null, // Will be generated by GenerateMonthlyNumber trait if applicable
            'tanggal' => $request->tanggal,
            'penjual_id' => $request->penjual_id,
            'supir_id' => $request->supir_id,
            'no_polisi' => $request->no_polisi,
            'tonase' => $request->tonase,
            'harga_satuan' => $request->harga_satuan,
            'sub_total' => $sub_total,
            'upah_bongkar' => $request->upah_bongkar ?? 0,
            'biaya_lain' => $request->biaya_lain ?? 0,
            'keterangan_biaya_lain' => $request->keterangan_biaya_lain,
            'cara_bayar' => $request->cara_bayar,
            'sisa_bayar' => $sub_total - ($request->upah_bongkar ?? 0) - ($request->biaya_lain ?? 0),
        ]);

        return response()->json($transaksi, 201);
    }
}
