<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\TransaksiDo;
use Illuminate\Http\Request;

class TransaksiDoController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $perusahaanId = $user->perusahaan_id;

        // Fail-safe untuk Admin/Superadmin tanpa perusahaan_id default
        if (is_null($perusahaanId)) {
            $perusahaanId = \App\Models\Perusahaan::first()?->id;
            if ($perusahaanId) {
                $user->update(['perusahaan_id' => $perusahaanId]);
            }
        }

        $query = TransaksiDo::withoutGlobalScopes()
            ->where('perusahaan_id', $perusahaanId)
            ->with(['penjual:id,nama', 'supir:id,nama']);

        if ($request->has('tanggal')) {
            $query->whereDate('tanggal', $request->tanggal);
        }

        return $query->latest()->paginate($request->per_page ?? 10);
    }

    public function show($id, Request $request)
    {
        $perusahaan_id = $request->user()->perusahaan_id;
        
        $transaksi = TransaksiDo::where('perusahaan_id', $perusahaan_id)
            ->with(['supir', 'kendaraan', 'penjual', 'detailTransaksiDo', 'pembayaranHutang'])
            ->findOrFail($id);

        return response()->json($transaksi);
    }

    public function store(Request $request)
    {
        $request->validate([
            'tanggal' => 'required|date',
            'penjual_id' => 'required|exists:penjual,id',
            'supir_id' => 'required|exists:supir,id',
            'no_polisi' => 'nullable|string',
            'tonase' => 'required|numeric',
            'harga_satuan' => 'required|numeric',
            'upah_bongkar' => 'nullable|numeric',
            'biaya_lain' => 'nullable|numeric',
            'keterangan_biaya_lain' => 'nullable|string',
            'pembayaran_hutang' => 'nullable|numeric|min:0',
            'cara_bayar' => 'required|in:tunai,transfer,cair di luar,belum dibayar',
            'bukti_transfer' => 'nullable|image|max:2048',
            'keterangan_pembayaran' => 'nullable|string',
        ]);

        $bukti_transfer_path = null;
        if ($request->hasFile('bukti_transfer')) {
            $bukti_transfer_path = $request->file('bukti_transfer')->store('bukti_transfer', 'public');
        }

        $penjual = \App\Models\Penjual::findOrFail($request->penjual_id);
        
        $sub_total = $request->tonase * $request->harga_satuan;
        $upah_bongkar = $request->upah_bongkar ?? 0;
        $biaya_lain = $request->biaya_lain ?? 0;
        $pembayaran_hutang = $request->pembayaran_hutang ?? 0;

        // Hitung sisa bayar (ke penjual)
        $sisa_bayar = max(0, $sub_total - ($upah_bongkar + $biaya_lain + $pembayaran_hutang));
        
        $transaksi = TransaksiDo::create([
            'perusahaan_id' => $request->user()->perusahaan_id,
            'nomor' => null, // Generated by observer/trait
            'tanggal' => $request->tanggal,
            'penjual_id' => $request->penjual_id,
            'supir_id' => $request->supir_id,
            'no_polisi' => $request->no_polisi,
            'tonase' => $request->tonase,
            'harga_satuan' => $request->harga_satuan,
            'upah_bongkar' => $upah_bongkar,
            'biaya_lain' => $biaya_lain,
            'keterangan_biaya_lain' => $request->keterangan_biaya_lain,
            'pembayaran_hutang' => $pembayaran_hutang,
            'cara_bayar' => $request->cara_bayar,
            'bukti_transfer' => $bukti_transfer_path,
            'keterangan_pembayaran' => $request->keterangan_pembayaran,
        ]);

        return response()->json($transaksi->load(['penjual', 'supir']), 201);
    }
}
